apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: project-management
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: apppassword
  JWT_SECRET: local-dev-secret-key-with-at-least-32-chars
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_DATABASE: Suivi_DB
  MYSQL_USER: appuser
  MYSQL_PASSWORD: apppassword
